# Generated by Django 5.0.2 on 2024-04-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_order_items_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='popular',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=100),
        ),
    ]
