# Generated by Django 5.0.2 on 2024-04-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_products_popular_alter_products_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items_json',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('No sugar', 'No sugar'), ('Fruit', 'Fruit'), ('Original', 'Original')], max_length=20),
        ),
    ]
