# Generated by Django 5.0.2 on 2024-04-20 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_order_items_order_items_json_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items_json',
            new_name='shopping_list',
        ),
    ]
