# Generated by Django 5.0.2 on 2024-05-09 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_items_json_order_shopping_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carditem',
            name='card',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card',
        ),
        migrations.RemoveField(
            model_name='carditem',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='CardItem',
        ),
    ]
