# Generated by Django 5.0.2 on 2024-06-19 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_orderitem_created_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shopping_list',
        ),
    ]
